"""AI Website Generator API routes."""

from __future__ import annotations

import logging
import uuid
import json
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field

from backend.api.auth import get_current_user
from database.models import User

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/websites", tags=["Website Generator"])

# In-memory store (production would use DB)
_website_projects: Dict[str, List[Dict[str, Any]]] = {}


class WebsiteGenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=5000, description="Website description")
    style: str = Field("modern", description="Style: modern, minimal, portfolio, business, creative")
    pages: List[str] = Field(default_factory=lambda: ["home"], description="Pages to generate")
    framework: str = Field("html", description="Framework: html, react, nextjs")
    include_css: bool = Field(True)
    dark_mode: bool = Field(True)


class WebsiteFile(BaseModel):
    filename: str
    content: str
    type: str


class WebsiteProject(BaseModel):
    id: str
    prompt: str
    style: str
    framework: str
    files: List[WebsiteFile]
    preview_html: str
    created_at: str
    status: str


def _generate_html_site(prompt: str, style: str, pages: List[str], dark_mode: bool) -> List[WebsiteFile]:
    """Generate a basic HTML website from a prompt."""
    bg = "#0f172a" if dark_mode else "#ffffff"
    fg = "#e2e8f0" if dark_mode else "#1e293b"
    accent = "#3b82f6"

    files = []
    nav_links = "".join(f'<a href="#{p}" class="nav-link">{p.title()}</a>' for p in pages)

    for page in pages:
        page_title = page.title()
        content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_title} - {prompt[:50]}</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: system-ui, -apple-system, sans-serif; background: {bg}; color: {fg}; }}
    .container {{ max-width: 960px; margin: 0 auto; padding: 2rem; }}
    nav {{ display: flex; gap: 1.5rem; padding: 1rem 2rem; border-bottom: 1px solid rgba(255,255,255,0.1); }}
    .nav-link {{ color: {fg}; text-decoration: none; font-size: 0.9rem; opacity: 0.7; }}
    .nav-link:hover {{ opacity: 1; color: {accent}; }}
    h1 {{ font-size: 2.5rem; margin-bottom: 1rem; color: {accent}; }}
    p {{ line-height: 1.8; margin-bottom: 1rem; opacity: 0.8; }}
    .hero {{ text-align: center; padding: 4rem 0; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; margin-top: 2rem; }}
    .card {{ background: rgba(255,255,255,0.05); border-radius: 12px; padding: 2rem; border: 1px solid rgba(255,255,255,0.1); }}
    footer {{ text-align: center; padding: 2rem; opacity: 0.5; font-size: 0.85rem; border-top: 1px solid rgba(255,255,255,0.1); margin-top: 4rem; }}
  </style>
</head>
<body>
  <nav>{nav_links}</nav>
  <div class="container">
    <div class="hero">
      <h1>{page_title}</h1>
      <p>{prompt}</p>
    </div>
    <div class="grid">
      <div class="card"><h3>Feature One</h3><p>Describe the first feature of your website here.</p></div>
      <div class="card"><h3>Feature Two</h3><p>Describe the second feature of your website here.</p></div>
      <div class="card"><h3>Feature Three</h3><p>Describe the third feature of your website here.</p></div>
    </div>
  </div>
  <footer>&copy; 2026 Generated by JARVIS</footer>
</body>
</html>"""
        fname = "index.html" if page == "home" else f"{page}.html"
        files.append(WebsiteFile(filename=fname, content=content, type="html"))

    return files


@router.get("", response_model=List[WebsiteProject])
async def list_projects(
    current_user: User = Depends(get_current_user),
):
    """List all website projects for the current user."""
    uid = str(current_user.id)
    return _website_projects.get(uid, [])


@router.post("", response_model=WebsiteProject, status_code=status.HTTP_201_CREATED)
async def generate_website(
    body: WebsiteGenerateRequest,
    current_user: User = Depends(get_current_user),
):
    """Generate a website from a prompt."""
    uid = str(current_user.id)
    project_id = str(uuid.uuid4())
    now = datetime.utcnow().isoformat()

    try:
        if body.framework == "html":
            files = _generate_html_site(body.prompt, body.style, body.pages, body.dark_mode)
        else:
            files = _generate_html_site(body.prompt, body.style, body.pages, body.dark_mode)

        # The first page is the preview
        preview = files[0].content if files else "<p>No preview available</p>"

        project = {
            "id": project_id,
            "prompt": body.prompt,
            "style": body.style,
            "framework": body.framework,
            "files": [f.model_dump() for f in files],
            "preview_html": preview,
            "created_at": now,
            "status": "completed",
        }

        if uid not in _website_projects:
            _website_projects[uid] = []
        _website_projects[uid].insert(0, project)

        return project
    except Exception as e:
        logger.error("Website generation failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@router.get("/{project_id}", response_model=WebsiteProject)
async def get_project(
    project_id: str,
    current_user: User = Depends(get_current_user),
):
    """Get a specific website project."""
    uid = str(current_user.id)
    for p in _website_projects.get(uid, []):
        if p["id"] == project_id:
            return p
    raise HTTPException(status_code=404, detail="Project not found")


@router.delete("/{project_id}")
async def delete_project(
    project_id: str,
    current_user: User = Depends(get_current_user),
):
    """Delete a website project."""
    uid = str(current_user.id)
    projects = _website_projects.get(uid, [])
    before = len(projects)
    _website_projects[uid] = [p for p in projects if p["id"] != project_id]
    if len(_website_projects[uid]) == before:
        raise HTTPException(status_code=404, detail="Project not found")
    return {"success": True}


@router.get("/{project_id}/export")
async def export_project(
    project_id: str,
    current_user: User = Depends(get_current_user),
):
    """Export website project files as JSON."""
    uid = str(current_user.id)
    for p in _website_projects.get(uid, []):
        if p["id"] == project_id:
            return {"files": p["files"], "framework": p["framework"]}
    raise HTTPException(status_code=404, detail="Project not found")
